# Experiment Metadata

# Data Configuration
dataset:
  name: "ktas-triage-multi" # Corresponds to your keys in utils_data._DATASETS
  start_index: 0
  end_index: 30  # Exclusive end index
  
# Model Configuration
model:
  name: "openai-o3-mini-chat" #openai-gpt-4o-high-quota-chat" #gpt-4o-mini"
  temperature: 0.0
  max_tokens: 1000
  top_p: 0.0
  return_json: False
  logprobs: False
  use_json_schema: False
  # Add any model-specific args here if needed (e.g., temperature)

# Prediction Strategy & Prompting
predictor: 
  strategy: "vanilla"
  k_shots: 0 # Set > 0 for few-shot strategies
# Output Configuration
filepaths:
  results_dir: "./results/"
  checkpoints_dir: "./results/checkpoints/"
  checkpoint_frequency: 250 # Save every N predictions

# Debugging
debug: False